package findaccount

// Additional known nodes, not all nodes from cosmos repo are live....

var additional = map[string][]string{
	"secretnetwork": {"tcp://scrt-rpc.blockpane.com:26657"},
	"osmosis":       {"https://osmosis-rpc.polkachu.com:443"},
	"chihuahua":     {"https://chihuahua-rpc.mercury-nodes.net:443"},
	"emoney":        {"https://emoney.validator.network:443"},
	"kava":          {"https://rpc.data.kava.io:443"},
	"stargaze":      {"https://rpc.stargaze-apis.com:443"},
	"juno":          {"https://juno-rpc.polkachu.com:443"},
}

// Prefixes maps the chain name to the bech32 address prefix.
// TODO: validate these are all correct!!!
var Prefixes = map[string]string{
	"agoric":         "agoric",
	"akash":          "akash",
	"assetmantle":    "mantle",
	"axelar":         "axelar",
	"bandchain":      "band",
	"bitcanna":       "bcn",
	"bitsong":        "bitsong",
	"bostrom":        "bostrom",
	"carbon":         "carbon",
	"cerberus":       "cerberus",
	"cheqd":          "cheqd",
	"chihuahua":      "chihuahua",
	"comdex":         "comdex",
	"cosmoshub":      "cosmos",
	"crescent":       "cre",
	"cronos":         "cro",
	"cryptoorgchain": "cro",
	"decentr":        "decentr",
	"desmos":         "desmos",
	"dig":            "dig",
	"emoney":         "emoney",
	"evmos":          "evmos",
	"fetchhub":       "fetchhub",
	"firmachain":     "firma",
	"galaxy":         "galaxy",
	"genesisl1":      "genesis",
	"gravitybridge":  "gravity",
	"impacthub":      "impact",
	"injective":      "inj",
	"irisnet":        "i",
	"juno":           "juno",
	"kava":           "kava",
	"kichain":        "ki",
	"konstellation":  "darc",
	"likecoin":       "like",
	"meme":           "meme",
	"microtick":      "micro",
	"nomic":          "nomic",
	"octa":           "octa",
	"odin":           "odin",
	"oraichain":      "orai",
	"osmosis":        "osmo",
	"panacea":        "panacea",
	"persistence":    "persistence",
	"provenance":     "pb",
	"regen":          "regen",
	"rizon":          "rizon",
	"secretnetwork":  "secret",
	"sentinel":       "sent",
	"shentu":         "certic",
	"sifchain":       "sif",
	"sommelier":      "somm",
	"stargaze":       "stars",
	"starname":       "star",
	"terra":          "terra",
	"umee":           "umee",
	"vidulum":        "vdl",
	// not working!!!
	//"arkh":           "arkh", //this is a testnet?
	//"echelon":        "echelon",
	//"logos":          "logos",
	//"lumnetwork":     "lum",
	//"mythos":         "mythos",
	//"thorchain":      "thor",
}
