package findaccount

// Additional known nodes, not all nodes from cosmos repo are live....

var additional = map[string][]string{
	"secretnetwork": {"tcp://scrt-rpc.blockpane.com:26657"},
	"osmosis":       {"https://osmosis-rpc.polkachu.com:443"},
	"chihuahua":     {"https://chihuahua-rpc.mercury-nodes.net:443"},
	"emoney":        {"https://emoney.validator.network:443"},
	"kava":          {"https://rpc.data.kava.io:443"},
	"stargaze":      {"https://rpc.stargaze-apis.com:443"},
	"juno":          {"https://juno-rpc.polkachu.com:443"},
}

// Prefixes maps the chain name to the bech32 address prefix.
// TODO: validate these are all correct!!!
var Prefixes = map[string]string{
	"agoric":    "agoric",
	"akash":     "akash",
	"axelar":    "axelar",
	"bandchain": "band",
	"cerberus":  "cerberus",
	"chihuahua": "chihuahua",
	"cosmoshub": "cosmos",
	"crescent":  "cre",
	//"desmos":        "desmos",
	"emoney": "emoney",
	"evmos":  "evmos",
	//"fetchhub":      "fetchhub",
	"firmachain":    "firma",
	"gravitybridge": "gravity",
	"impacthub":     "impact",
	"juno":          "juno",
	"kava":          "kava",
	"konstellation": "darc",
	"microtick":     "micro",
	"nomic":         "nomic",
	"octa":          "octa",
	"odin":          "odin",
	"oraichain":     "orai",
	"osmosis":       "osmo",
	"regen":         "regen",
	"rizon":         "rizon",
	"secretnetwork": "secret",
	"shentu":        "certic",
	"sifchain":      "sif",
	"stargaze":      "stars",
	"terra":         "terra",

	// not working!!!

	//"arkh": "arkh",
	//"assetmantle":    "assetmantle",
	//"bitcanna":       "bcn",
	//"bitsong":        "bitsong",
	//"bostrom":       "bostrom",
	//"carbon":         "carbon",
	//"cheqd":          "cheqd",
	//"comdex":         "comdex",
	//"cronos":         "cro",
	//"cryptoorgchain": "cro",
	//"decentr":        "decentr",
	//"dig":            "dig",
	//"echelon":        "echelon",
	//"galaxy":         "galaxy",
	//"genesisl1":      "genesis",
	//"injective":      "inj",
	//"irisnet":        "i",
	//"kichain":        "ki",
	//"likecoin":       "like",
	//"logos":          "logos",
	//"lumnetwork":     "lum",
	//"meme":           "meme",
	//"mythos":         "mythos",
	//"panacea":        "panacea",
	//"persistence":    "persistence",
	//"provenance":     "pb",
	//"sentinel":       "sent",
	//"sommelier":      "somm",
	//"starname":       "star",
	//"thorchain":      "thor",
	//"umee":           "umee",
	//"vidulum":        "vdl",
}
